name: Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  mocha:
    name: Mocha
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18, 19, 20, 21]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
        env:
          CI: true
      - name: Run Mocha tests
        run: npm test
